export const initialAppointments = [
    {
      id: 'APPT-101',
      time: '08:30 AM',
      patientId: 'PTNT-005',
      patientName: 'John Doe',
      age: 42,
      sex: 'Male',
      contact: '0917-111-2233',
      address: '12 Acacia St., Quezon City',
      emergencyName: 'Jane Doe',
      emergencyContact: '0917-222-3344',
      type: 'Routine Checkup',
      doctor: 'Dr. Cruz',
      room: 'General Intake A',
      date: 'Sept 19, 2026',
      status: 'Confirmed',
      notes: 'Annual physical examination and routine blood pressure screening.',
    },
    {
      id: 'APPT-102',
      time: '09:00 AM',
      patientId: 'PTNT-006',
      patientName: 'Maria Santos',
      age: 29,
      sex: 'Female',
      contact: '0918-333-4455',
      address: '45 Emerald Ave., Pasig City',
      emergencyName: 'Carlos Santos',
      emergencyContact: '0918-444-5566',
      type: 'General Consultation',
      doctor: 'Dr. Santos',
      room: 'General Intake A',
      date: 'Sept 19, 2026',
      status: 'Checked-In',
      notes: 'Consultation for mild seasonal cough and throat irritation.',
    },
    {
      id: 'APPT-103',
      time: '09:30 AM',
      patientId: null,
      patientName: '*Available Slot*',
      age: null,
      sex: null,
      contact: '',
      address: '',
      emergencyName: '',
      emergencyContact: '',
      type: 'Standard Intake',
      doctor: 'Dr. Santos',
      room: 'General Intake A',
      date: 'Sept 19, 2026',
      status: 'Open',
      notes: 'Open appointment window for walk-in triage or advance booking.',
    },
    {
      id: 'APPT-104',
      time: '10:00 AM',
      patientId: 'PTNT-007',
      patientName: 'Robert Reyes',
      age: 51,
      sex: 'Male',
      contact: '0922-555-6677',
      address: '78 Mabini St., Manila',
      emergencyName: 'Elena Reyes',
      emergencyContact: '0922-666-7788',
      type: 'Follow-up (Routine)',
      doctor: 'Dr. Reyes',
      room: 'General Intake A',
      date: 'Sept 19, 2026',
      status: 'Confirmed',
      notes: 'Follow-up on laboratory panel results and prescription renewal.',
    },
    {
      id: 'APPT-105',
      time: '10:30 AM',
      patientId: 'PTNT-002',
      patientName: 'Allen Tracy',
      age: 21,
      sex: 'Female',
      contact: '0919-345-6789',
      address: '789 Quezon Ave., Quezon City',
      emergencyName: 'Robert Tracy',
      emergencyContact: '0919-765-4321',
      type: 'Follow up',
      doctor: 'Dr. Rebuyaco',
      room: 'Consultation Room 1',
      date: 'Sept 19, 2026',
      status: 'Confirmed',
      notes: 'Follow-up evaluation for resolving allergic rhinitis.',
    },
    {
      id: 'APPT-106',
      time: '11:00 AM',
      patientId: 'PTNT-001',
      patientName: 'Juan Dela Cruz',
      age: 34,
      sex: 'Male',
      contact: '0991-123-1245',
      address: '143 Jose St., Malabon City',
      emergencyName: 'Maria Dela Cruz',
      emergencyContact: '0991-123-1245',
      type: 'Routine Checkup',
      doctor: 'Dr. Cruz',
      room: 'General Intake A',
      date: 'Sept 19, 2026',
      status: 'Checked-In',
      notes: 'Hypertension checkup, follow-up on Amlodipine 5mg regimen.',
    },
    {
      id: 'APPT-107',
      time: '11:30 AM',
      patientId: null,
      patientName: '*Available Slot*',
      age: null,
      sex: null,
      contact: '',
      address: '',
      emergencyName: '',
      emergencyContact: '',
      type: 'General Wellness',
      doctor: 'Dr. Reyes',
      room: 'General Intake A',
      date: 'Sept 19, 2026',
      status: 'Open',
      notes: 'Open slot available for immediate booking.',
    },
    {
      id: 'APPT-108',
      time: '01:30 PM',
      patientId: 'PTNT-003',
      patientName: 'Richiebelle Del Rosario',
      age: 16,
      sex: 'Female',
      contact: '0918-234-5678',
      address: '456 Taft Ave., Pasay City',
      emergencyName: 'Susan Del Rosario',
      emergencyContact: '0918-876-5432',
      type: 'Consultation',
      doctor: 'Dr. Santos',
      room: 'General Intake A',
      date: 'Sept 19, 2026',
      status: 'Confirmed',
      notes: 'Pediatric respiratory follow-up consultation.',
    },
    {
      id: 'APPT-109',
      time: '02:00 PM',
      patientId: 'PTNT-004',
      patientName: 'John Smith',
      age: 19,
      sex: 'Male',
      contact: '0920-456-7890',
      address: '321 Shaw Blvd., Mandaluyong City',
      emergencyName: 'Carlos Smith',
      emergencyContact: '0920-654-3210',
      type: 'Routine Checkup',
      doctor: 'Dr. Reyes',
      room: 'General Intake A',
      date: 'Sept 19, 2026',
      status: 'Confirmed',
      notes: 'Routine fitness verification exam.',
    },
    {
      id: 'APPT-110',
      time: '02:30 PM',
      patientId: null,
      patientName: '*Available Slot*',
      age: null,
      sex: null,
      contact: '',
      address: '',
      emergencyName: '',
      emergencyContact: '',
      type: 'Standard Intake',
      doctor: 'Dr. Santos',
      room: 'General Intake A',
      date: 'Sept 19, 2026',
      status: 'Open',
      notes: 'Afternoon open slot for clinical intake.',
    },
  ];
